---

services:
  app:
    image: "dgiorgio/gvm-feed-server"
    hostname: "gvm-feed-server"
    container_name: "gvm_feed_server"
    restart: always
    ports:
      - "873:873"
    volumes:
      - "data:/data"
      - "log:/var/log"
      - "/etc/localtime:/etc/localtime:ro"

volumes:
  data:
  log:
