name: "Build and Push GVM Feed Docker Image"

on:
  workflow_dispatch:  # Apenas acionamento manual

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: ./build.sh

      - name: Push Docker image
        run: ./build.sh push
